apiVersion: apps/v1
kind: Deployment
metadata:
  name: updatecrew
  namespace: eksapp
  labels:
    app: updatecrew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: updatecrew
  template:
    metadata:
      labels:
        app: updatecrew
    spec:
      containers:
        - name: updatecrew
          image: 265083127752.dkr.ecr.us-east-1.amazonaws.com/ecr-update-crew-repo
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
