kind: Service
apiVersion: v1
metadata:
  name: updatecrew
  namespace: eksapp
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: 8080
	  protocol: TCP
  selector:
    app: updatecrew
